export const categories = [
  { id: 1, name: "Electronics" },
  { id: 2, name: "Books" },
  { id: 3, name: "Clothing" },
  { id: 4, name: "Home" },
  { id: 5, name: "Toys" },
  { id: 6, name: "Sports" },
  { id: 7, name: "Beauty" },
  { id: 8, name: "Automotive" },
  { id: 9, name: "Garden" },
  { id: 10, name: "Health" },
];

export const product = [
  {
    id: 1,
    name: "Alpha Product",
    price: 29.99,
    sold: 100,
    categoryId: 1,
    rate: 4.5,
    description:
      "This is a great product for your daily needs. It is reliable and affordable.",
    variants: ["Red", "Blue", "Green"],
    image: ["https://picsum.photos/seed/picsum1/200/300", "https://picsum.photos/seed/picsum1a/200/300", "https://picsum.photos/seed/picsum1b/200/300", "https://picsum.photos/seed/picsum1c/200/300"]
  },
  {
    id: 2,
    name: "Beta Item",
    price: 19.99,
    sold: 150,
    categoryId: 2,
    rate: 3.8,
    description:
      "A must-have item for your collection. It offers great value for money.",
    variants: ["Small", "Medium", "Large"],
    image: ["https://picsum.photos/seed/picsum2/200/300", "https://picsum.photos/seed/picsum2a/200/300", "https://picsum.photos/seed/picsum2b/200/300", "https://picsum.photos/seed/picsum1c/200/300"],
  },
  {
    id: 3,
    name: "Gamma Deluxe Product",
    price: 39.99,
    sold: 200,
    categoryId: 3,
    rate: 4.2,
    description:
      "Experience the luxury with this deluxe product. Perfect for special occasions.",
    variants: ["Round", "Square"],
    image: ["https://picsum.photos/seed/picsum3/200/300", "https://picsum.photos/seed/picsum3a/200/300", "https://picsum.photos/seed/picsum3b/200/300", "https://picsum.photos/seed/picsum3c/200/300"],
  },
  {
    id: 4,
    name: "Delta Ultimate Edition",
    price: 49.99,
    sold: 250,
    categoryId: 4,
    rate: 4.7,
    description:
      "The ultimate edition of our popular product. Enhanced features and performance.",
    variants: ["Black", "White"],
    image: ["https://picsum.photos/seed/picsum4/200/300", "https://picsum.photos/seed/picsum4a/200/300", "https://picsum.photos/seed/picsum4b/200/300", "https://picsum.photos/seed/picsum4c/200/300"],
  },
  {
    id: 5,
    name: "Epsilon Product",
    price: 59.99,
    sold: 300,
    categoryId: 5,
    rate: 4.0,
    description:
      "A versatile product that meets all your needs. High quality and durability.",
    variants: ["Red", "Blue", "Green", "Yellow"],
    image: ["https://picsum.photos/seed/picsum5/200/300", "https://picsum.photos/seed/picsum5a/200/300", "https://picsum.photos/seed/picsum5b/200/300", "https://picsum.photos/seed/picsum5c/200/300"],
  },
  {
    id: 6,
    name: "Zeta Premium Item",
    price: 69.99,
    sold: 350,
    categoryId: 6,
    rate: 3.9,
    description:
      "Premium quality item with exceptional features. Ideal for discerning customers.",
    variants: ["Small", "Medium", "Large", "Extra Large"],
    image: ["https://picsum.photos/seed/picsum6/200/300", "https://picsum.photos/seed/picsum6a/200/300", "https://picsum.photos/seed/picsum6b/200/300", "https://picsum.photos/seed/picsum6c/200/300"],
  },
  {
    id: 7,
    name: "Eta Super Deluxe Product",
    price: 79.99,
    sold: 400,
    categoryId: 7,
    rate: 4.3,
    description:
      "Super deluxe product with top-notch features. Perfect for those who want the best.",
    variants: ["Round", "Square", "Triangle"],
    image: ["https://picsum.photos/seed/picsum7/200/300", "https://picsum.photos/seed/picsum7a/200/300", "https://picsum.photos/seed/picsum7b/200/300", "https://picsum.photos/seed/picsum7c/200/300"],
  },
  {
    id: 8,
    name: "Theta Item",
    price: 89.99,
    sold: 450,
    categoryId: 8,
    rate: 4.1,
    description:
      "A reliable item that you can count on. Great for everyday use.",
    variants: ["Black", "White", "Gray"],
    image: ["https://picsum.photos/seed/picsum8/200/300", "https://picsum.photos/seed/picsum8a/200/300", "https://picsum.photos/seed/picsum8b/200/300", "https://picsum.photos/seed/picsum8c/200/300"],
  },
  {
    id: 9,
    name: "Iota Special Edition Product",
    price: 99.99,
    sold: 500,
    categoryId: 9,
    rate: 4.6,
    description:
      "Special edition product with unique features. Limited availability.",
    variants: ["Red", "Blue"],
    image: ["https://picsum.photos/seed/picsum9/200/300", "https://picsum.photos/seed/picsum9a/200/300", "https://picsum.photos/seed/picsum9b/200/300", "https://picsum.photos/seed/picsum9c/200/300"],
  },
  {
    id: 10,
    name: "Kappa Limited Edition Product",
    price: 109.99,
    sold: 550,
    categoryId: 10,
    rate: 4.4,
    description:
      "Limited edition product with exclusive features. A collector's item.",
    variants: ["Small", "Medium"],
    image: ["https://picsum.photos/seed/picsum10/200/300", "https://picsum.photos/seed/picsum10a/200/300", "https://picsum.photos/seed/picsum10b/200/300", "https://picsum.photos/seed/picsum10c/200/300"],
  },
  {
    id: 11,
    name: "Lambda Product",
    price: 119.99,
    sold: 600,
    categoryId: 1,
    rate: 4.8,
    description:
      "High-quality product with excellent performance. Highly recommended.",
    variants: ["Round", "Square"],
    image: ["https://picsum.photos/seed/picsum11/200/300", "https://picsum.photos/seed/picsum11a/200/300", "https://picsum.photos/seed/picsum11b/200/300", "https://picsum.photos/seed/picsum11c/200/300"],
  },
  {
    id: 12,
    name: "Mu Item",
    price: 129.99,
    sold: 650,
    categoryId: 2,
    rate: 4.2,
    description:
      "A valuable item that offers great functionality. Perfect for daily use.",
    variants: ["Black", "White", "Gray"],
    image: ["https://picsum.photos/seed/picsum12/200/300", "https://picsum.photos/seed/picsum12a/200/300", "https://picsum.photos/seed/picsum12b/200/300", "https://picsum.photos/seed/picsum12c/200/300"],
  },
  {
    id: 13,
    name: "Nu Product",
    price: 139.99,
    sold: 700,
    categoryId: 3,
    rate: 4.0,
    description:
      "A reliable product with great features. Ideal for all your needs.",
    variants: ["Red", "Blue", "Green"],
    image: ["https://picsum.photos/seed/picsum13/200/300", "https://picsum.photos/seed/picsum13a/200/300", "https://picsum.photos/seed/picsum13b/200/300", "https://picsum.photos/seed/picsum13c/200/300"],
  },
  {
    id: 14,
    name: "Xi Item",
    price: 149.99,
    sold: 750,
    categoryId: 4,
    rate: 3.7,
    description:
      "An essential item for your collection. Offers great value and performance.",
    variants: ["Small", "Medium", "Large"],
    image: ["https://picsum.photos/seed/picsum14/200/300", "https://picsum.photos/seed/picsum14a/200/300", "https://picsum.photos/seed/picsum14b/200/300", "https://picsum.photos/seed/picsum14c/200/300"],
  },
  {
    id: 15,
    name: "Omicron Product",
    price: 159.99,
    sold: 800,
    categoryId: 5,
    rate: 4.5,
    description:
      "A top-quality product with outstanding features. Perfect for special occasions.",
    variants: ["Round", "Square", "Triangle"],
    image: ["https://picsum.photos/seed/picsum15/200/300", "https://picsum.photos/seed/picsum15a/200/300", "https://picsum.photos/seed/picsum15b/200/300", "https://picsum.photos/seed/picsum15c/200/300"],
  },
  {
    id: 16,
    name: "Pi Item",
    price: 169.99,
    sold: 850,
    categoryId: 6,
    rate: 4.1,
    description:
      "A versatile item that meets all your needs. High quality and durability.",
    variants: ["Black", "White"],
    image: ["https://picsum.photos/seed/picsum16/200/300", "https://picsum.photos/seed/picsum16a/200/300", "https://picsum.photos/seed/picsum16b/200/300", "https://picsum.photos/seed/picsum16c/200/300"],
  },
  {
    id: 17,
    name: "Rho Product",
    price: 179.99,
    sold: 900,
    categoryId: 7,
    rate: 4.3,
    description:
      "A premium product with exceptional features. Ideal for discerning customers.",
    variants: ["Red", "Blue", "Green", "Yellow"],
    image: ["https://picsum.photos/seed/picsum17/200/300", "https://picsum.photos/seed/picsum17a/200/300", "https://picsum.photos/seed/picsum17b/200/300", "https://picsum.photos/seed/picsum17c/200/300"],
  },
  {
    id: 18,
    name: "Sigma Item",
    price: 189.99,
    sold: 950,
    categoryId: 8,
    rate: 4.6,
    description:
      "A reliable item that you can count on. Great for everyday use.",
    variants: ["Small", "Medium", "Large", "Extra Large"],
    image: ["https://picsum.photos/seed/picsum18/200/300", "https://picsum.photos/seed/picsum18a/200/300", "https://picsum.photos/seed/picsum18b/200/300", "https://picsum.photos/seed/picsum18c/200/300"],
  },
  {
    id: 19,
    name: "Tau Product",
    price: 199.99,
    sold: 1000,
    categoryId: 9,
    rate: 4.7,
    description:
      "A special edition product with unique features. Limited availability.",
    variants: ["Round", "Square"],
    image: ["https://picsum.photos/seed/picsum19/200/300", "https://picsum.photos/seed/picsum19a/200/300", "https://picsum.photos/seed/picsum19b/200/300", "https://picsum.photos/seed/picsum19c/200/300"],
  },
  {
    id: 20,
    name: "Upsilon Item",
    price: 209.99,
    sold: 1050,
    categoryId: 10,
    rate: 4.9,
    description:
      "A limited edition product with exclusive features. A collector's item.",
    variants: ["Black", "White", "Gray"],
    image: ["https://picsum.photos/seed/picsum20/200/300", "https://picsum.photos/seed/picsum20a/200/300", "https://picsum.photos/seed/picsum20b/200/300", "https://picsum.photos/seed/picsum20c/200/300"],
  },
  {
    id: 21,
    name: "Handcrafted Frozen Table",
    price: 26.00,
    sold: 45124,
    categoryId: 3,
    rate: 2.56,
    description:
      "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
    variants: ["I","K"],
    image: ["https://picsum.photos/seed/picsum21/200/300", "https://picsum.photos/seed/picsum21a/200/300", "https://picsum.photos/seed/picsum21b/200/300", "https://picsum.photos/seed/picsum21c/200/300"]
  },
  {
    id: 22,
    name: "Incredible Concrete Sausages",
    price: 365.00,
    sold: 1166,
    categoryId: 2,
    rate: 2.74,
    description:
      "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
    variants: ["D","F"],
    image: ["https://picsum.photos/seed/picsum22/200/300", "https://picsum.photos/seed/picsum22a/200/300", "https://picsum.photos/seed/picsum22b/200/300", "https://picsum.photos/seed/picsum22c/200/300"],
  },
  {
    id: 23,
    name: "Gorgeous Fresh Sausages",
    price: 867.00,
    sold: 3638,
    categoryId: 6,
    rate: 4.57,
    description:
      "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
    variants: ["U","S"],
    image: ["https://picsum.photos/seed/picsum23/200/300", "https://picsum.photos/seed/picsum23a/200/300", "https://picsum.photos/seed/picsum23b/200/300", "https://picsum.photos/seed/picsum23c/200/300"],
  },
  {
    id: 24,
    name: "Elegant Wooden Chicken",
    price: 514.00,
    sold: 2362,
    categoryId: 9,
    rate: 3.03,
    description:
      "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
    variants: ["V","X"],
    image: ["https://picsum.photos/seed/picsum24/200/300", "https://picsum.photos/seed/picsum24a/200/300", "https://picsum.photos/seed/picsum24b/200/300", "https://picsum.photos/seed/picsum24c/200/300"],
  },
  {
    id: 25,
    name: "Sleek Rubber Soap",
    price: 966.00,
    sold: 9468,
    categoryId: 2,
    rate: 4.41,
    description:
      "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
    variants: ["A", "I"],
    image: ["https://picsum.photos/seed/picsum25/200/300", "https://picsum.photos/seed/picsum25a/200/300", "https://picsum.photos/seed/picsum25b/200/300", "https://picsum.photos/seed/picsum25c/200/300"],
  },
  {
    id: 26,
    name: "Electronic Granite Fish",
    price: 212.00,
    sold: 93327,
    categoryId: 9,
    rate: 4.75,
    description:
      "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
    variants: ["H", "I"],
    image: ["https://picsum.photos/seed/picsum26/200/300", "https://picsum.photos/seed/picsum26a/200/300", "https://picsum.photos/seed/picsum26b/200/300", "https://picsum.photos/seed/picsum26c/200/300"],
  },
  {
    id: 27,
    name: "Incredible Rubber Cheese",
    price: 40.00,
    sold: 7982,
    categoryId: 3,
    rate: 2.88,
    description:
      "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
    variants: ["W", "F"],
    image: ["https://picsum.photos/seed/picsum27/200/300", "https://picsum.photos/seed/picsum27a/200/300", "https://picsum.photos/seed/picsum27b/200/300", "https://picsum.photos/seed/picsum27c/200/300"],
  },
  {
    id: 28,
    name: "Elegant Bronze Bike",
    price: 18.00,
    sold: 2540,
    categoryId: 10,
    rate: 4.88,
    description:
      "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
    variants: ["F", "A"],
    image: ["https://picsum.photos/seed/picsum28/200/300", "https://picsum.photos/seed/picsum28a/200/300", "https://picsum.photos/seed/picsum28b/200/300", "https://picsum.photos/seed/picsum28c/200/300"],
  },
  {
    id: 29,
    name: "Intelligent Fresh Mouse",
    price: 657.00,
    sold: 5799,
    categoryId: 5,
    rate: 3.40,
    description:
      "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
    variants: ["E", "Q"],
    image: ["https://picsum.photos/seed/picsum29/200/300", "https://picsum.photos/seed/picsum29a/200/300", "https://picsum.photos/seed/picsum29b/200/300", "https://picsum.photos/seed/picsum29c/200/300"],
  },
  {
    id: 30,
    name: "Generic Plastic Bike",
    price: 648.00,
    sold: 70685,
    categoryId: 5,
    rate: 1.60,
    description:
      "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
    variants: ["L", "B"],
    image: ["https://picsum.photos/seed/picsum30/200/300", "https://picsum.photos/seed/picsum30a/200/300", "https://picsum.photos/seed/picsum30b/200/300", "https://picsum.photos/seed/picsum30c/200/300"],
  },
];
